### ISSUE TITLE
Notebook in Curriculum branch is not valid JSON

### ISSUE THREAD

**Issue by Cheffrey2000** [learn-co-curriculum/dsc-git-branches#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

## Describe the Issue
Curriculum branch jupyter notebook is broken. Github says it is not valid json. The notebook works fine in VS code, but will not render in github website.
### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
works fine in notebooks as well. I cannot get it to render in nbviewer online. But the README looks fine and that appears to be rendering fine in [Canvas](https://learning.flatironschool.com/courses/6948/pages/collaborating-with-git-branches) at this time so I wouldn't worry about the .ipynb not rendering on GitHub
